set mouse=a
set numberwidth=1
set clipboard=unnamedplus
set hidden
set nohlsearch
set noswapfile
set nobackup
set nowritebackup
set incsearch
set scrolloff=15
set showcmd
set ruler
set encoding=utf-8
set showmatch
set expandtab
set sw=2
set softtabstop=2
set tabstop=2
set relativenumber
set laststatus=2
set wrap 
set noshowmode
set splitright
set diffopt+=vertical
set updatetime=100
set shortmess+=c
set nocompatible
set t_Co=256
set termguicolors
