set mouse=a
set colorcolumn=101,120
set numberwidth=2
set clipboard+=unnamedplus
set hidden
set nohlsearch
set noswapfile
set nobackup
set nowritebackup
set incsearch
set scrolloff=8
set showcmd
set ruler
set encoding=utf-8
set showmatch
set expandtab
set sw=2
set softtabstop=2
set tabstop=2
set number
set relativenumber
set cursorline
" set cursorlineopt=number
set laststatus=2
set wrap 
set noshowmode
set splitright
set diffopt+=vertical
set updatetime=50
set shortmess+=c
set nu
