#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/nvim/lua/clarkyex
mkdir -p ~/.config/nvim/lua/helpers
mkdir -p ~/.config/nvim/lua/common

# link wholesale
for f in `find . -name "*.lua" -o -name "*.vim"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/configs/nvim/$f ~/.config/nvim/$f
done
