#!/usr/bin/env bash
keymap=$1
currentSession=$(tmux display-message -p '#S')
    case "$keymap" in
    "G")
      case "$currentSession" in
        "mma"*)
          tmux switch -t mma-api
          ;;
        *) echo "Unavailable command... $curr"
      esac
      ;;
    "C")
      case "$currentSession" in
        "mma"*)
          tmux switch -t mma-app
          ;;
        *) echo "Nothing fonud"
      esac
        ;;
    "R")
      case "$currentSession" in
        "mma"*)
          tmux switch -t mma-contracts
          ;;
        *) echo "Nothing fonud"
      esac
       ;;
    "L")
      case "$currentSession" in
      esac
        ;;
    "D")
      case "$currentSession" in
        *) echo "Nothing fonud"
      esac
        ;;
    "S")
      case "$currentSession" in
        *) echo "Nothing fonud"
      esac
        ;;
    *) echo "Unavailable command... $curr"
    esac
